### ISSUE TITLE
Can't change profile in tube amp

### ISSUE THREAD

**Issue by sandysingssongs** [olegkapitonov/Kapitonov-Plugins-Pack#3] opened 2019-02-28 14:28 UTC
The plugin looks and sounds great but I can't change the profile from 'American Clean' or switch between clean and crunch in Ardour. I've tried clicking, double clicking, right clicking, middle clicking - all to no avail. I'm really looking forward to hearing the other models. Thanks and keep up the good work!

**Comment by ChekPuk** [comment] 2019-02-28 16:09
I get the same in Qtractor. If I change profile file in Tubeamps GUI, gtk file choosing dialogue opens, I select file, but nothing hapends. If I change it in Qtractors native interface, then it works (but it opens Qt file choosing dialogue). Open GUI again, and it shows old profile. Everything except profile changing works in GUI.

**Comment by brummer10** [comment] 2019-02-28 16:22
I can't switch between crunch and clean as well here, changing profile seems to require zenity to be installed.

**Comment by sandysingssongs** [comment] 2019-02-28 17:26
> changing profile seems to require zenity to be installed.

Thanks for that. I'll try it tomorrow.

**Comment by olegkapitonov** [comment] 2019-03-01 04:29
Yes, Zenity is required to change the profile, I entirely forgot to mention this in description, sorry! There is no standard file select dialog for pure X11 GUI in LV2 plugins.

**Comment by sandysingssongs** [comment] 2019-03-01 05:20
> I entirely forgot to mention this in description, sorry!

No problem.

**Comment by olegkapitonov** [comment] 2019-03-01 08:35
I updated README and Quick Start Guide, wrote about zenity.

**Comment by REIS0** [comment] 2020-10-29 23:47
Updating that I'm with this problem, currently using the last binaries with Pop_OS! 20.04, zenity 3.32.0 installed and working (tested commands for example `zenity calendar`)

**Comment by olegkapitonov** [comment] 2020-10-31 09:24
Hello, @REIS0!

This is strange. Since 1.2 release threre is no zenity dependency anymore,
file choose dialog is native X11 and it should work if main tubeAmp GUI works.

Are you shure that you try the latest 1.2.1 release?

**Comment by sub26nico** [comment] 2020-10-31 09:51
IIRC, with the vst3, the profiles are not found but it is possible to point the profiles files folder and load it. Here, no problems with lv2.

**Comment by sub26nico** [comment] 2020-10-31 12:18
Note that there is no profiles files or folder  in /usr/lib/vst3/Vkpp_tubeamp.vst3/ here (Debian10). The profiles files are only in /usr/lib/lv2/kpp_tubeamp.lv2/profiles/.

**Comment by sub26nico** [comment] 2020-10-31 15:33
My bad, profiles files are in /usr/share/kapitonov-plugins-pack-vst3/tubeAmp Profiles/ for vst3.

**Comment by REIS0** [comment] 2020-10-31 23:35
@olegkapitonov yes even tried removing and making a complete new install using binaries from github and website today, the problem still persists, I'm currently trying to check for any logs or anything that can give a hint on what's going on but until now haven't found any.

**Comment by olegkapitonov** [comment] 2020-11-01 09:48
@REIS0 I tried to reproduce this on Pop!_OS 20.04 on the virtual machine with Ardour5 as host. All works fine on my setup.

Which host do you use? Do you try LV2 or VST3 versions of the plugins?

**Comment by REIS0** [comment] 2020-11-01 18:57
@olegkapitonov The LV2 version with Carla and Ardour, and the same problem in both.

Tried testing if I could reproduce this in a virtual machine too and got the same thing. [Here's a video](https://www.youtube.com/watch?v=jPierPVj1U0) showing the problem in the virtual machine.

**Comment by trebmuh** [comment] 2020-11-01 19:02
AFAIK, the Crunch/Clean switch [isn't implemented yet](https://github.com/olegkapitonov/Kapitonov-Plugins-Pack/issues/6#issuecomment-542913574).

**Comment by REIS0** [comment] 2020-11-01 19:03
@trebmuh oh, so i guess it's solved...

**Comment by olegkapitonov** [comment] 2020-11-05 10:27
So I'm closing this :)

**Closed as completed by olegkapitonov** 2020-11-05 10:27 UTC
